try {
    throw("Error")
}
catch(err) {
  console.log(err)
}